# Generated by Django 3.2.18 on 2023-04-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='emote_users',
        ),
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Emote_post',
        ),
    ]
