# Generated by Django 3.2.18 on 2023-05-04 01:45

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text=False, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='#해쉬태그(필수)'),
        ),
    ]
